# Numoy In Python

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]], np.int64)

In [3]:
myarr[0] 

array([ 3,  6, 32,  7], dtype=int64)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0,1] = 45

In [21]:
myarr

array([[ 3, 45, 32,  7]], dtype=int64)

---

## Array creation: Conversion from other Python Structured

#### Using Lists 

In [9]:
listarray = np.array([[1,2,3],[4,5,6],[0,3,1]])

In [10]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [0, 3, 1]])

#### Adding a dictionary

In [12]:
np.array({34,23,23})

array({34, 23}, dtype=object)

---

## Intrinsic numpy array creation objects

#### Zeroes

In [13]:
zeroes = np.zeros((2,5))

In [14]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### Range

In [17]:
rng = np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Linspace

In [27]:
lspace = np.linspace(1,50,10)

In [28]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

#### Empty

In [29]:
emp = np.empty((4,6))

In [30]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        4.00542154e-307, 6.23045126e-307, 8.45593934e-307],
       [7.56593017e-307, 1.11258854e-306, 1.11261502e-306,
        1.42410839e-306, 7.56597770e-307, 6.23059726e-307],
       [1.42419530e-306, 7.56602523e-307, 1.29061821e-306,
        1.78020169e-306, 1.33511290e-306, 1.78019082e-306],
       [8.45559303e-307, 9.45697982e-308, 1.33511562e-306,
        8.90103560e-307, 1.42410974e-306, 3.23796840e-317]])

In [31]:
emp_like = np.empty_like(lspace)

In [33]:
emp_like

<function empty_like at 0x00000178594DF930>

#### Identity matrix

In [34]:
ide = np.identity(45)

In [35]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [36]:
ide.shape

(45, 45)